import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  testMatch: [
    '**/dashboard-freshness.spec.ts',
    '**/action-column-contract.spec.ts',
    '**/admin-content-accessibility.spec.ts',
    '**/admin-profile-draft.spec.ts',
    '**/approval-date-guard.spec.ts',
    '**/bangkok-date.spec.ts',
    '**/branch-location-order.spec.ts',
    '**/branch-rubber-receipt.spec.ts',
    '**/export-vehicle-weigh-bill-timing.spec.ts',
    '**/immediate-mutation-state-contract.spec.ts',
    '**/income-sale-calculations.spec.ts',
    '**/income-sale-approval-contract.spec.ts',
    '**/integration-target.spec.ts',
    '**/location-preference.spec.ts',
    '**/money-transfer-slip-validation.spec.ts',
    '**/money-transfer-state.spec.ts',
    '**/offline-module-policy.spec.ts',
    '**/ocr-slip.spec.ts',
    '**/ocr-slip-route.spec.ts',
    '**/report-date.spec.ts',
    '**/reports/report-presentation.spec.ts',
    '**/reports/report-query-chunks.spec.ts',
    '**/rubber-bill-approval-cache.spec.ts',
    '**/rubber-bill-calculations.spec.ts',
    '**/rubber-bill-print.spec.ts',
    '**/rubber-bill-validation.spec.ts',
    '**/rubber-weight-alert-state.spec.ts',
    '**/rubber-bills/rubber-bill-ocr-queue.spec.ts',
    '**/rubber-evidence-selectors.spec.ts',
    '**/rubber-export-age.spec.ts',
    '**/rubber-export-calculations.spec.ts',
    '**/rubber-export-presentation.spec.ts',
    '**/scoped-single-flight.spec.ts',
    '**/sync-response.spec.ts',
    '**/supabase-pages.spec.ts',
    '**/time-payroll-period-state.spec.ts',
    '**/time-payroll-slip-document.spec.ts',
    '**/time-tracking-employee-list.spec.ts',
    '**/time-tracking-pay.spec.ts',
  ],
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: 0,
  reporter: 'list',
  workers: process.env.CI ? 2 : undefined,
});
